#+title: System rebuild script using nushell
#+PROPERTY: header-args:nushell :noweb yes :mkdirp yes :tangle rebuild.nu

Simple script for rebuilding the system in one command.
Self-note: This file will not auto-tangle, and needs to be tangled manually using ~C-c C-v t~

We'll start by getting into my dotfiles if I'm not alreaedy there and defining a timer variable. I'll use this to generate a list of each section's time at the end of the script.

#+begin_src nushell
#!/usr/bin/env nu

mut timer = []

cd ~/.dotfiles
#+end_src

First we'll add files to git. Using Jujitsu would be simpler but I'm not there yet.
Note the ~$timer~ variable in use. I'm using nushell's ~timeit~ command to time each section, and It'll build a nice list at the end of how long the process took.

#+begin_src nushell
print "/---- Adding files to git ----/ \n"
$timer ++= [{step: "git add", time: (timeit { git add . })}]
print "/---- Files added ----/ \n"
#+end_src

We then need to tangle the org files. Since I'm converting to a literate config, every file in the config starts life as an org file. Org-mode is a markdown like language native to emacs that has several nifty features for documentation and plain organizing your life around. You can learn more about it [[https://orgmode.org/][here]].
Tangling is org-mode's way of taking every code block in a file and putting them together in a separate config file of your choosing. Here for example, this document's code block will be "tangled" into ~rebuild.nu~, a useable nushell script in the same directory.
This means that the org file becomes the sole source of truth, both in documentation and in code.

#+begin_src nushell
print "/---- Tangling org files ----/ \n"
$timer ++= [{step: "tangle org files", time: (timeit {
       glob **/*.org | where ($it | path basename) != "README.org" | each { |f| let eval_str = '(org-babel-tangle-file "' + ($f | str trim) + '")'
       emacs --batch -l org --eval $eval_str
       }
})}]
print "/---- Tangle done ----/ \n"
#+end_src

We'll then rebuild the system with the classic ~nixos-rebuild~ command

#+begin_src nushell
print "/---- Rebuilding NixOS ----/ \n"
$timer ++= [{step:"NixOS rebuild", time: (timeit { sudo nixos-rebuild switch --flake $".#(hostname)" })}]
print "/---- NixOS rebuilt ----/ \n"
#+end_src

Next we commit to git and add a commit comment

#+begin_src nushell
print "/---- Committing to git ----/ \n"
let default_msg = $"NixOS (date now | format date '%Y-%m-%dT%H:%M:%S%z') Build (hostname) (readlink /nix/var/nix/profiles/system | path basename | split row '-' | get 1)"
let user_msg = (input $"Commit message \(($default_msg)\): ")
let commit_msg = if ($user_msg | str trim | is-empty) { $default_msg } else { $"($user_msg)\n($default_msg)" }
$timer ++= [{step: "Git commit", time: (timeit { git commit -m $commit_msg })}]
print "/---- Changes commited to git ----/ \n"
#+end_src

And finally we push it to the remote, in this case github (But not for long! I have a deep seated hate for Microsoft whose fiery embers have been forged in the early aughts.)

#+begin_src nushell
print "/---- Pushing to remote ----/ \n"
$timer ++= [{step: "Git push", time: (timeit { git push })}]
print "/---- Pushed to remote ----/ \n"
#+end_src

Now that everything is done, It's time for a short summary. We need to round out times to not go into nano and micro seconds.

#+begin_src nushell
print "/---- Summary ----/ \n"
print ($timer | update time { |row| ($row.time / 1ms | math round) * 1ms } | table)
let total = ($timer | get time | math sum)
print $"System rebuilt in: (($total / 1ms | math round) * 1ms)"
#+end_src
