#+title: Emacs configuration file
#+property: header-args :noweb yes :mkdirp yes :tangle no
#+property: header-args:nix :tangle emacs.nix

This file tangles into ~emacs.nix~, ~doom.d/config.el~, ~doom.d/init.el~ and ~doom.d/packages.el.~

I never thought I'd say this, but I completely switched from neovim to emacs, mainly because of [[https://orgmode.org/][Org-mode]]. I would never have switched if I couldn't have my vim keybindings, and those are very well supported via evil-mode, which we can get in [[https://github.com/doomemacs/doomemacs][Doom Emacs]], a ready made distribution of emacs that is optimized and caters to vimers like me. Plus the logo is just cool.

* emacs.nix

First we need to to define our nix module.

**  Module definition and package wrangling


Next, we need to nixify it, so we'll use [[https://github.com/marienz/nix-doom-emacs-unstraightened][nix-doom-emacs-unstraightened]] (oof) since it helps us bypass straight.el and manages our packages for us :D
Since we're using unstraightened (even then it's too long) as a flake with home-manager, we first need to import the module. Then we'll tell it where our Doom config will live (here in a subfolder caller ~doom.d~).

Finally, I'm also adding vterm for terminal support inside emacs and [[https://github.com/emacsmirror/mu4e][mu4e]], an email client inside emacs. Nifty!

The all-grammars line is a fix for tree-sitter which currently behaves eratically across multiple programs since the author archived it. Each definition is very small, so adding all grammars does not add a lot of overhead.

#+begin_src nix
{ inputs, ... }:
{
  flake.modules.homeManager.emacs = { pkgs, ... }: {
    imports = [ inputs.nix-doom-emacs-unstraightened.homeModule ];

    programs.doom-emacs = {
      enable = true;
      doomDir = ./doom.d;
      emacs = pkgs.emacs-pgtk;
      extraPackages = epkgs: [
        epkgs.vterm
        epkgs.mu4e
        epkgs.treesit-grammars.with-all-grammars
      ];
    };
#+end_src

** Emacs as a server

One of the understated advantages of emacs is being able to run it as a server and have new frames attach to it automatically. This has several benefits here:
- Doom Emacs is started just the once, meaning that actually opening an emacs frame (the app) is, wait for it, *Blazingly Fast*.
- Since the daemon is running in the background, processes like mu4e or the killring (copy-paste) don't have to restart between frames, you just reattach each time. It also means you can have several frames opened that link to the same buffers (Let's say you have one instance and another in the terminal for example).
- I also use it as a global org-mode capture with a hotkey in niri ( ~Mod+C~ ) that make noting things on the fly a breeeze.

We'll also start mbsync, which is necessary for mu4e.

#+begin_src nix
    services = {
      emacs.enable = true;
      mbsync.enable = true;
    };
#+end_src

** Some dependencies and protonmail.

While we're talking about mu4e, here's the other shoe: We need isync and mu, so we're pulling them here, along with hunspell (for spelling in org-mode), and then I'm using protonmail, so I need to set up the protonmail bridge to pipe my email correctly into it.

#+begin_src nix
    home.packages = [
      pkgs.mu
      pkgs.isync
      pkgs.hunspell
      pkgs.hunspellDicts.en_US
      pkgs.hunspellDicts.fr-any
    ];
    systemd.user.services.protonmail-bridge = {
      Unit = {
        Description = "ProtonMail Bridge";
        After = [ "network-online.target" ];
      };
      Service = {
        ExecStart = "${pkgs.protonmail-bridge}/bin/protonmail-bridge --noninteractive";
        Restart = "always";
      };
      Install = {
        WantedBy = [ "default.target" ];
      };
    };
  };
}

#+end_src

* Doom Config

The Doom config comes in three files, ~init.el~, ~config.el~ and ~packages.el~. They all have their purpose which I'll explain below. Normally, you'd want to either reload the config after each edit of these files (done with ~SPC h r r~) but since we're using ~Unstraightened~,

** Init (init.el)
:PROPERTIES:
:header-args:emacs-lisp: :tangle doom.d/init.el
:END:

The init.el serves as an options menu with many possibilities. There are more than these but these ones are mine. They are commented by Doom Emacs by default, I've left them there for the explanation (or funny).

#+begin_src emacs-lisp
(doom! :completion
       (corfu +orderless)        ; complete with cap(f), cape and a flying feather!
       vertico                   ; the search engine of the future

       :ui
       doom                      ; what makes DOOM look the way it does
       dashboard                 ; a nifty splash screen for Emacs
       (emoji +unicode)          ; 🙂
       hl-todo                   ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       indent-guides             ; highlighted indent columns
       ligatures                 ; ligatures and symbols to make your code pretty again
       modeline                  ; snazzy, Atom-inspired modeline, plus API
       nav-flash                 ; blink cursor line after big motions
       ophints                   ; highlight the region an operation acts on
       (popup +defaults)         ; tame sudden yet inevitable temporary windows
       smooth-scroll             ; So smooth you won't believe it's not butter
       (vc-gutter +pretty)       ; vcs diff in the fringe
       vi-tilde-fringe           ; fringe tildes to mark beyond EOB
       workspaces                ; tab emulation, persistence & separate workspaces

       :editor
       (evil +everywhere)        ; come to the dark side, we have cookies
       file-templates            ; auto-snippets for empty files
       fold                      ; (nigh) universal code folding
       (format +onsave)          ; automated prettiness
       multiple-cursors          ; editing in many places at once
       snippets                  ; my elves. They type so I don't have to
       (whitespace +guess +trim) ; a butler for your whitespace
       word-wrap                 ; soft wrapping with language-aware indent

       :emacs
       dired                     ; making dired pretty [functional]
       electric                  ; smarter, keyword-based electric-indent
       tramp                     ; remote files at your arthritic fingertips
       undo                      ; persistent, smarter undo for your inevitable mistakes

       :term
       vterm                     ; the best terminal emulation in Emacs

       :checkers
       syntax                    ; tasing you for every semicolon you forget
       (spell +hunspell)         ; tasing you for misspelling mispelling

       :tools
       direnv
       editorconfig              ; let someone else argue about tabs vs spaces
       (eval +overlay)           ; run code, run (also, repls)
       lookup                    ; navigate your code and its documentation
       (lsp +eglot)              ; M-x vscode
       magit                     ; a git porcelain for Emacs
       pdf                       ; pdf enhancements
       tree-sitter               ; syntax and parsing, sitting in a tree...

       :os
       tty                       ; improve the terminal Emacs experience

       :lang
       data                      ; config/data formats
       emacs-lisp                ; drown in parentheses
       (go +lsp)                 ; the hipster dialect
       json                      ; At least it ain't XML
       lua                       ; one-based indices? one-based indices
       markdown                  ; writing docs for people to ignore
       nix                       ; I hereby declare "nix geht mehr!"
       (org +roam2)              ; organize your plain life in plain text
       graphviz                  ; diagrams for confusing yourself even more
       python                    ; beautiful is better than ugly
       (rust +lsp)               ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       sh                        ; she sells {ba,z,fi}sh shells on the C xor
       yaml                      ; JSON, but readable
       zig                       ; C, but simpler

       :email
       (mu4e +org +mbsync)        ; Email client, requires mu, mpd, and for me, protonmail-bridge.

       :app
       calendar                  ; As the name suggests, it is a calendar.
       emms                      ; A media player in my text editor? Really?
       erc                       ; how neckbeards socialize
       (rss +org)                ; emacs as an RSS reader

       :config
       (default +bindings +smartparens))
#+end_src

** Config (config.el)
:PROPERTIES:
:header-args:emacs-lisp: :tangle doom.d/config.el
:END:

*** Directory settings and username

Now That we've set up our options, we can configure a lot of Emacs (and Doom) through ~config.el~.

First a bit of boilerplate. We'll set up a few things required for [[https://orgmode.org/][Org-mode]], [[https://github.com/bbatsov/projectile][Projectile]] and setting the term to zsh because I couldn't make nushell work (for now) reliably inside emacs. Finally I'm setting my name and email.

#+begin_src emacs-lisp
(setq shell-file-name "/etc/profiles/per-user/ghil/bin/zsh"
      org-directory "~/org/"
      org-roam-directory "~/org/roam"
      projectile-project-search-path '("~/projects/")
      user-full-name "Guillaume Labrie"
      user-mail-address "glabrie@proton.me")
#+end_src

*** Aesthetics and themes

We'll then set the theme and fonts.  I'm also still using Tokyo Night as my main theme.
small note: In the Doom documentation you'll find ~Doom-unicode-font~. It's been deprecated and we're now using ~doom-symbol-font~.

Finally, we'll be adding some transparency to the frames to get that ~Niri~ blur to show through.

**** Fonts

I'm using a mixed pitch where the prose is displayed in [[https://www.fontspace.com/montserrat-font-f16544][Montserrat]] while the code is displayed in [[https://www.jetbrains.com/lp/mono/][JetBrains Mono]].
It makes for a nice separation that make prose look like documentation, while the code is still eminently readable in a mono font.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 18)
      doom-variable-pitch-font (font-spec :family "Montserrat")
      doom-symbol-font (font-spec :family "JetBrainsMono Nerd Font" :size 18)
      doom-big-font (font-spec :family "Maple Mono NF" :size 24))
#+end_src

**** Theme

I'm using Tokyo Night everywhere else in the system, so this gets applied here as well.

#+begin_src emacs-lisp
(setq doom-theme 'doom-tokyo-night)
#+end_src

**** Relative lines - The vim way

As I'm coming from vim, and still uses the keybindings daily, I need my relative lines. This gives me that, with another setting to correct the numbers to their actual position:

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode +1)
#+end_src

**** Let the frames breathe

#+begin_src emacs-lisp
(modify-all-frames-parameters
 '((right-divider-width . 12)
   (internal-border-width . 12)))
(dolist (face '(window-divider
                window-divider-first-pixel
                window-divider-last-pixel))
  (face-spec-reset-face face)
  (set-face-foreground face (face-attribute 'default :background)))
(set-face-background 'fringe (face-attribute 'default :background))
#+end_src

**** Transparency

Niri now has a beautiful blur, which we're taking advantage of by setting the opacity to 80%

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 80))
(set-frame-parameter nil 'alpha-background 80)
#+end_src

**** Org-modern

[[https://github.com/minad/org-modern][Org-modern]] is a nice way to format ~Org-mode~ automatically. It's very pretty, customizable. I recommend it!
Normally, org-mode doesn't parse your notes recursively for todos, for performance reasons. I'll set up something better someday, but for now just a dirty trick to make it check recursively so that it can get to my ~org-roam~ daily notes folder.

#+begin_src emacs-lisp
(after! org
  (setq org-auto-align-tags nil
        org-tags-column 0
        org-catch-invisible-edits 'show-and-error
        org-special-ctrl-a/e t
        org-insert-heading-respect-content t
        org-hide-emphasis-markers t
        org-pretty-entities t
        org-ellipsis " ⮯"
        org-agenda-tags-column 0
        org-agenda-block-separator ?─
        org-agenda-time-grid
        '((daily today require-timed)
          (800 1000 1200 1400 1600 1800 2000)
          " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
        org-agenda-current-time-string
        "◀── now ─────────────────────────────────────────────────"
        org-agenda-files
          (directory-files-recursively org-directory "\\.org$")))

(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq org-modern-star 'replace
        org-modern-block-fringe nil))

(add-hook 'text-mode-hook #'mixed-pitch-mode)
#+end_src

*** Keybindings

The rare custom keybinds I run are to get to my notes faster, and a graph that you'll look at once, go "wow, that's neat" and probably never open again, just like in ~Obsidian~. Yay!

#+begin_src emacs-lisp
(map! :leader
      :desc "Capture daily" "n d" #'org-roam-dailies-capture-today
      :desc "Go to daily" "n D" #'org-roam-dailies-goto-today
      :desc "Org-roam UI graph" "n r g" #'org-roam-ui-mode)
#+end_src

*** Org-roam

#+begin_src emacs-lisp
(after! org-roam
  (require 'org-roam-ui)
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))

(setq org-roam-dailies-capture-templates
        '(("d" "default" entry
           "* %?"
           :target (file+head "%<%Y-%m-%d>.org"
                              "#+title: %<%Y-%m-%d>\n"))
          ("w" "weekly review" entry
           "* %<%Y-W%V> Weekly review                                  :weekly:
[[id:WEEKLY-REVIEW-NODE-ID][Weekly Review]]

,** Summary of the week
%?

,** Wins

,** Misses

,** What to keep in mind moving forward

,** Planning the next: What needs doing?
"
           :target (file+head "%<%Y-%m-%d>.org"
                              "#+title: %<%Y-%m-%d>\n"))))
#+end_src

*** Org-capture global capture key


#+begin_src emacs-lisp
(defun +my/org-capture-fullscreen-in-dedicated-frame (&rest _)
  (when (equal (frame-parameter nil 'name) "org-capture")
    (delete-other-windows)))
(add-hook 'org-capture-mode-hook #'+my/org-capture-fullscreen-in-dedicated-frame)
(advice-add 'org-roam-dailies-capture-today
            :after #'+my/org-capture-fullscreen-in-dedicated-frame)

(defun +my/org-capture-cleanup-frame (&rest _)
  (when (equal (frame-parameter nil 'name) "org-capture")
    (delete-frame)))
(advice-add 'org-capture-finalize :after #'+my/org-capture-cleanup-frame)

(add-hook '+doom-dashboard-inhibit-functions
          (lambda () (equal (frame-parameter nil 'name) "org-capture")))
#+end_src

*** Mu4e


#+begin_src emacs-lisp
(after! mu4e
  (setq mu4e-update-interval 120
        mu4e-change-filenames-when-moving t
        mu4e-trash-folder "/Trash"
        mu4e-sent-folder "/Sent"
        mu4e-drafts-folder "/Drafts"
        mu4e-refile-folder "/Archive"
        mu4e-personal-addresses '("glabrie@proton.me" "ghil@hey.com" "glabrie85@gmail.com")
        mu4e-view-prefer-html t
        shr-max-image-proportion 0.0
        shr-color-visible-luminance-min 80
        shr-use-colors nil))
#+end_src

*** Browser not opening links fix

I have this weird thing where since I've switched to emacs as a daemon, it doesn't want to open links anymore. This is a quick fix for that. I should investigate more. I have seen on the net that it might be because of the environment and selecting a display too soon. More on this some other time.

#+begin_src emacs-lisp
(setq browse-url-browser-function 'browse-url-generic
      browse-url-generic-program "zen")
#+end_src

** Packages (packages.el)
:PROPERTIES:
:header-args:emacs-lisp: :tangle doom.d/packages.el
:END:

#+begin_src emacs-lisp
(package! kdl-mode)
(package! org-modern)
(package! org-roam-ui)
(package! mixed-pitch)
#+end_src
