#+title: Starship configuration file
#+property: header-args:nix :noweb yes :mkdirp yes :tangle starship.nix
#+property: header-args:toml :noweb yes :mkdirp yes :tangle starship.toml

This file tangles into ~starship.nix~ and ~starship.toml~

* Introduction

Starship is a cross-platform shell prompt that I've been using for a number of years now. It's fast, fun and customizeable. Plus, you can apply the same config to more than one shell, which is always a good bonus. And of course, it's written in Rust :P
To learn more about Starship, click [[https://starship.rs/][here]].

* NixOS module

The module itself is very simple. We're declaring, in addition to the program itself, the integration of both zsh AND nushell. I'm using nushell everywhere nowadays except in one specific place, and that's emacs' internal terminal, vterm. I'm looking for a solution to this, but in the meantime, zsh stays.

#+begin_src nix
{ ... }:
{
  flake.modules.homeManager.starship =
  { pkgs, ... }:
  {
    programs.starship = {
      enable = true;
      enableZshIntegration = true;
      enableNushellIntegration = true;
      settings = pkgs.lib.importTOML ./starship.toml;
    };
  };
}
#+end_src

* Starship toml configuration file

Starship is configured with the TOML configuration language, which you can find more about [[https://toml.io/en/][here]].

I don't like it overly flashy, but I like some pizzaz for, say it with me, ✨ /aesthetics/ ✨.
I'm using a preset from starship for tokyo-night that I find pretty and unobstructive. I barely modified it, you can find it on the starship website!

First thing I'm establishing is the format, or how it will look at the end of it.

#+begin_src toml
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$time\
[](fg:color_bg1)\
$line_break$character"""

palette = 'tokyo_night'

[palettes.tokyo_night]
color_fg0 = '#e3e5e5'
color_bg1 = '#1d2230'
color_bg3 = '#1d2230'
color_blue = '#212736'
color_aqua = '#394260'
color_green = '#9ece6a'
color_orange = '#a3aed2'
color_purple = '#bb9af7'
color_red = '#f7768e'
color_yellow = '#769ff0'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
NixOS = "󰄄"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

#+end_src

Then we'll configure everything that goes in it, starting with a module to show where you are in the tree.

#+begin_src toml
[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
#+end_src

Then I'll specify a lot of symbols to correctly tell starship what it should be rendering.

#+begin_src toml
[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[bun]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#e3e5e5 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#e3e5e5 bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'
#+end_src

And the last module is a simple clock

#+begin_src toml

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
#+end_src
